/* COPYRIGHT (C) HARRY CLARK 2024 */
/* CS2_IAI STUDY MATERIAL */

/* THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF THE PROGRAM */

/* NESTED INCLUDES */

#include "peas.h"

/* CHANGE WHICH MAIN FUNCTION YOU WANT TO USE HERE */
/* I COULD MAKE A SEPERATE MAKEFILE FOR EACH FOLDER FOR EACH SUBJECT AREA BUT I CAN'T BE ARSED */

int main(void)
{
    RING_MAIN();
    return 0;
}
